(()=>{
const KEY='myTrainingSchedule',PROGRAM_KEY='myTrainingProgramme';
const pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,today=()=>iso(new Date());
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const labels=['MON','TUE','WED','THU','FRI','SAT','SUN'];let viewDate=new Date(new Date().getFullYear(),new Date().getMonth(),1),open=false,editing=false,editingDays=null;
const programme=()=>read(PROGRAM_KEY),schedule=()=>read(KEY)||[];
const doneIds=()=>{const out=new Set(),d=read('myTrainingDashboard');Object.entries(d?.logs||{}).forEach(([k,v])=>{if(v?.done){const id=k.split('::')[1];if(id)out.add(id)}});return out};
const completedDates=()=>{const out=new Set(),d=read('myTrainingDashboard');Object.entries(d?.logs||{}).forEach(([k,v])=>{if(v?.done)out.add(k.split('::')[0])});return out};
const nextRequired=()=>{const done=doneIds();return (window.PROGRAM||[]).find(w=>!done.has(w.id))?.id||null};
const addDays=(date,n)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return iso(d)};
const nextDates=(days,count,start,blocked=new Set())=>{const out=[],d=new Date(`${start}T12:00:00`);for(let g=0;out.length<count&&g<730;g++){const s=iso(d);if(days.includes((d.getDay()+6)%7)&&!blocked.has(s))out.push(s);d.setDate(d.getDate()+1)}return out};
const nav=a=>`<nav class="nav"><button onclick="calendarNav('home')" class="${a==='home'?'active':''}">⌂<span>Home</span></button><button onclick="calendarNav('calendar')" class="${a==='calendar'?'active':''}">▣<span>Calendar</span></button><button onclick="calendarNav('plan')" class="${a==='plan'?'active':''}">☷<span>Plan</span></button><button onclick="calendarNav('progress')" class="${a==='progress'?'active':''}">⌁<span>Progress</span></button></nav>`;
function render(html){document.body.innerHTML=html}
function setup(){const p=programme(),days=editingDays??p?.days??[];return `<main class="shell"><div class="top"><div><div class="eyebrow">Calendar</div><div class="title">${editing?'Change training days':'Set your training days'}</div><div class="sub">Choose four normal training days. Programme order stays locked.</div></div></div><div class="card"><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px">${labels.map((x,i)=>`<button class="${days.includes(i)?'primary':'pill'}" style="padding:12px 4px" onclick="calendarDay(${i})">${x}</button>`).join('')}</div><button class="primary" style="width:100%;margin-top:18px" ${days.length===4?'':'disabled'} onclick="calendarSaveDays()">${editing?'Save training days':'Start programme'}</button>${editing?'<button class="text-link" onclick="calendarCancel()">Cancel <span>×</span></button>':''}</div></main>${nav('calendar')}`}
function page(){const p=programme();if(!p?.active)return setup();const a=schedule(),done=completedDates(),required=nextRequired(),y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,total=Math.ceil((offset+last.getDate())/7)*7;let cells='';for(let i=0;i<total;i++){const n=i-offset+1;if(n<1||n>last.getDate()){cells+='<div class="calendar-cell empty"></div>';continue}const date=`${y}-${pad(m+1)}-${pad(n)}`,x=a.find(q=>q.date===date),past=date<today(),complete=done.has(date),due=x?.id===required&&!complete,state=x?(complete?'workout':past?'missed':'workout future'):'';cells+=`<button class="calendar-cell ${state} ${date===today()?'today':''}" ${x?`onclick="calendarWorkout('${x.id}')"`:''}><span class="calendar-number">${n}</span>${x?`<span class="calendar-mark">${complete?'✓':past?'×':'●'}</span><small style="display:block;font-size:9px;margin-top:3px">#${x.id}${due?' DUE':''}</small>`:''}</button>`}return `<main class="shell calendar-modern"><section class="calendar-header"><div><h1>${viewDate.toLocaleDateString('en-GB',{month:'long',year:'numeric'}).toUpperCase()}</h1><button class="calendar-edit" onclick="calendarEdit()">Edit training days</button></div><div class="calendar-actions"><button onclick="calendarMonth(-1)">‹</button><button class="calendar-today" onclick="calendarToday()">▣</button><button onclick="calendarMonth(1)">›</button></div></section><div class="calendar-weekdays">${labels.map(x=>`<span>${x[0]}</span>`).join('')}</div><div class="calendar-grid">${cells}</div><div class="card"><b>Programme order is locked</b><div class="muted" style="margin-top:5px">A missed workout remains due until you complete it. Changing dates never skips a workout.</div></div></main>${nav('calendar')}`}
window.calendarNav=s=>{if(s==='calendar'){open=true;render(page());return}open=false;if(originalGo)originalGo(s)};
window.calendarMonth=n=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+n,1);render(page())};window.calendarToday=()=>{const d=new Date();viewDate=new Date(d.getFullYear(),d.getMonth(),1);render(page())};
window.calendarEdit=()=>{editing=true;editingDays=[...(programme()?.days||[])];render(setup())};window.calendarCancel=()=>{editing=false;editingDays=null;render(page())};
window.calendarDay=i=>{const days=[...(editingDays??programme()?.days??[])],at=days.indexOf(i);if(at>=0)days.splice(at,1);else if(days.length<4)days.push(i);editingDays=days;render(setup())};
window.calendarSaveDays=()=>{const days=editingDays??programme()?.days??[];if(days.length!==4)return;if(!programme()?.active){const dates=nextDates(days,(window.PROGRAM||[]).length,today());save(PROGRAM_KEY,{active:true,days,startDate:dates[0]});save(KEY,(window.PROGRAM||[]).map((w,i)=>({id:w.id,date:dates[i]})))}else{const old=schedule(),td=today(),done=completedDates(),fixed=old.filter(x=>x.date<=td||done.has(x.date)),moving=old.filter(x=>x.date>td&&!done.has(x.date)).sort((a,b)=>String(a.id).localeCompare(String(b.id))),dates=nextDates(days,moving.length,addDays(td,1),new Set(fixed.map(x=>x.date)));moving.forEach((x,i)=>x.date=dates[i]);save(PROGRAM_KEY,{...programme(),days});save(KEY,[...fixed,...moving])}editing=false;editingDays=null;render(page())};
window.calendarWorkout=id=>{const required=nextRequired();if(required&&id!==required){alert(`Workout #${required} is still due. Complete it before moving on.`);return}open=false;if(window.choose)window.choose(id)};
let originalGo=null,originalStart=null,installed=false;
function install(){if(installed||typeof window.go!=='function'||typeof window.start!=='function')return;originalGo=window.go;originalStart=window.start;window.go=s=>s==='calendar'?window.calendarNav('calendar'):originalGo(s);window.start=()=>{const id=nextRequired();if(id&&window.choose)window.choose(id);originalStart()};installed=true;ensureNav()}
function ensureNav(){if(open)return;const n=document.querySelector('.nav');if(!n||n.querySelector('[data-cal-added]'))return;const b=document.createElement('button');b.dataset.calAdded='1';b.innerHTML='▣<span>Calendar</span>';b.onclick=()=>window.calendarNav('calendar');n.insertBefore(b,n.children[1]||null)}
new MutationObserver(()=>{install();ensureNav()}).observe(document.documentElement,{childList:true,subtree:true});setInterval(()=>{install();ensureNav()},500);install();
})();