(()=>{
const KEY='myTrainingSchedule', PROGRAM_KEY='myTrainingProgramme';
const pad=n=>String(n).padStart(2,'0');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=()=>iso(new Date());
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const programme=()=>read(PROGRAM_KEY);
const schedule=()=>read(KEY)||[];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const dayKey=(y,m,d)=>`${y}-${pad(m+1)}-${pad(d)}`;
const monthName=d=>d.toLocaleDateString('en-GB',{month:'long',year:'numeric'}).toUpperCase();
const labels=['MON','TUE','WED','THU','FRI','SAT','SUN'];
let viewDate=new Date(new Date().getFullYear(),new Date().getMonth(),1);
let calendarOpen=false,setupOpen=false,editing=false,editingDays=null,startWrapped=false;
const icons={
 dumbbell:`<svg class="calendar-icon dumbbell" viewBox="0 0 44 30" aria-hidden="true"><path d="M7 8v14M2 10v10M12 5v20M32 5v20M37 8v14M42 10v10M12 15h20" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`,
 trophy:`<svg class="calendar-icon trophy" viewBox="0 0 44 34" aria-hidden="true"><path d="M14 4h16v8c0 6-3 10-8 10s-8-4-8-10V4Z" fill="none" stroke="currentColor" stroke-width="2.5"/><path d="M14 7H7v3c0 5 3 7 7 7M30 7h7v3c0 5-3 7-7 7M22 22v5M16 30h12" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
 calendar:`<svg class="calendar-head-icon" viewBox="0 0 28 28" aria-hidden="true"><rect x="3" y="5" width="22" height="20" rx="2" fill="none" stroke="currentColor" stroke-width="2.5"/><path d="M8 3v5M20 3v5M3 11h22" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><circle cx="19" cy="19" r="3" fill="currentColor"/></svg>`
};
function completedDates(){const out=new Set(),data=read('myTrainingDashboard');Object.entries(data?.logs||{}).forEach(([k,v])=>{if(v?.done){const d=k.split('::')[0];if(d)out.add(d)}});return out}
function prDates(){const out=new Set(),data=read('myTrainingDashboard');const has=v=>{if(!v||typeof v!=='object')return false;if(Array.isArray(v))return v.some(has);return Object.entries(v).some(([k,x])=>(/(^|_|-)(pr|personal.?best|personal.?record)(_|-|$)/i.test(k)&&(x===true||(Array.isArray(x)&&x.length)||(x&&typeof x==='object')))||has(x))};Object.entries(data?.logs||{}).forEach(([k,v])=>{if(has(v)){const d=k.split('::')[0];if(d)out.add(d)}});return out}
function nextDates(days,count,start,blocked=new Set()){const out=[],d=new Date(`${start}T12:00:00`);for(let guard=0;out.length<count&&guard<730;guard++){const s=iso(d);if(days.includes((d.getDay()+6)%7)&&!blocked.has(s))out.push(s);d.setDate(d.getDate()+1)}return out}
function writeProgramme(days){const dates=nextDates(days,window.PROGRAM.length,today());save(PROGRAM_KEY,{active:true,days,startDate:dates[0],startedAt:new Date().toISOString()});save(KEY,window.PROGRAM.map((w,i)=>({id:w.id,date:dates[i]})))}
function rescheduleFuture(days){const old=schedule(),td=today(),done=completedDates();const fixed=old.filter(x=>x?.date<=td||done.has(x?.date));const moving=old.filter(x=>x?.date>td&&!done.has(x?.date)).sort((a,b)=>String(a.id).localeCompare(String(b.id)));const blocked=new Set(fixed.map(x=>x.date));const dates=nextDates(days,moving.length,addDays(td,1),blocked);moving.forEach((x,i)=>{if(dates[i])x.date=dates[i]});save(PROGRAM_KEY,{...(programme()||{}),active:true,days});save(KEY,[...fixed,...moving].sort((a,b)=>String(a.id).localeCompare(String(b.id))));}
function addDays(date,n){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return iso(d)}
function render(html){const app=document.getElementById('app');if(app)app.innerHTML=html;else document.body.innerHTML=`<div id="app">${html}</div>`}
function nav(active){return `<nav class="nav"><button type="button" class="${active==='home'?'active':''}" onclick="calendarNav('home')">⌂<span>Home</span></button><button type="button" data-calendar="1" class="${active==='calendar'?'active':''}" onclick="calendarNav('calendar')">▣<span>Calendar</span></button><button type="button" class="${active==='plan'?'active':''}" onclick="calendarNav('plan')">☷<span>Plan</span></button><button type="button" class="${active==='progress'?'active':''}" onclick="calendarNav('progress')">⌁<span>Progress</span></button></nav>`}
function setupPage(){const p=programme(),selected=(editingDays??p?.days??[]),title=editing?'Change training days':'Start your programme',button=editing?'Save training days':'Start programme',copy=editing?'Completed and past sessions stay where they are. Only future sessions move to the new days.':'Choose the four days you normally want to train. Your 20-workout programme will be placed on those days.';return `<main class="shell programme-setup"><div class="top"><div><div class="eyebrow">My Training</div><div class="title">${title}</div><div class="sub">20 workouts · 4 sessions per week</div></div></div><section class="card programme-card"><h2>Choose your training days</h2><p class="muted">${copy}</p><div class="training-day-picker">${labels.map((x,i)=>`<button type="button" class="training-day ${selected.includes(i)?'selected':''}" onclick="toggleTrainingDay(${i})"><b>${x}</b><span>${selected.includes(i)?'✓':'+'}</span></button>`).join('')}</div><div class="programme-preview"><div><span class="muted">Programme</span><b>20 workouts</b></div><div><span class="muted">Frequency</span><b>4 days / week</b></div><div><span class="muted">First session</span><b>${selected.length===4?new Date(`${nextDates(selected,1,today())[0]}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'Choose 4 days'}</b></div></div><button type="button" class="primary programme-start" ${selected.length===4?'':'disabled'} onclick="startProgramme()">${button} <span>›</span></button>${editing?'<button type="button" class="text-link" onclick="cancelProgrammeEdit()">Cancel <span>×</span></button>':''}</section></main>${nav('calendar')}`}
function calendarPage(){const p=programme();if(!p?.active)return setupPage();const a=schedule(),done=completedDates(),prs=prDates(),y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,total=Math.ceil((offset+last.getDate())/7)*7;let cells='';for(let i=0;i<total;i++){const n=i-offset+1;if(n<1||n>last.getDate()){cells+='<div class="calendar-cell empty"></div>';continue}const date=dayKey(y,m,n),x=a.find(q=>q.date===date),completed=done.has(date),pr=prs.has(date),isToday=date===today(),past=date<today();const state=x?(completed?'workout':past?'missed':'workout future'):'';const mark=pr?icons.trophy:x?(completed?icons.dumbbell:past?'<span class="missed-x">×</span>':icons.dumbbell):'';cells+=`<button type="button" class="calendar-cell ${state} ${isToday?'today':''} ${pr?'pr':''}" aria-label="${esc(x?`Workout #${x.id}`:isToday?'Today':'No workout')}" onclick="calendarDay('${date}')"><span class="calendar-number">${n}</span><span class="calendar-mark">${mark}</span></button>`}return `<main class="shell calendar-modern"><section class="calendar-header"><div><h1>${monthName(viewDate)}</h1><button type="button" class="calendar-edit" onclick="editProgramme()">Edit training days</button></div><div class="calendar-actions"><button type="button" aria-label="Previous month" onclick="calendarMonth(-1)">‹</button><button type="button" class="calendar-today" aria-label="Go to current month" onclick="calendarToday()">${icons.calendar}</button><button type="button" aria-label="Next month" onclick="calendarMonth(1)">›</button></div></section><div class="calendar-weekdays">${labels.map(x=>`<span>${x[0]}</span>`).join('')}</div><div class="calendar-grid">${cells}</div></main>${nav('calendar')}`}
window.calendarNav=screen=>{if(screen==='calendar'){calendarOpen=true;setupOpen=false;render(calendarPage());return}calendarOpen=false;setupOpen=false;if(typeof window.go==='function')window.go(screen)};
window.renderCalendar=()=>{calendarOpen=true;render(calendarPage())};
window.toggleTrainingDay=i=>{const p=programme()||{days:[]},days=[...(editingDays??p.days??[])],at=days.indexOf(i);if(at>=0)days.splice(at,1);else if(days.length<4)days.push(i);else return;editingDays=days;setupOpen=true;render(setupPage())};
window.startProgramme=()=>{const days=editingDays??programme()?.days??[];if(days.length!==4)return;if(editing)rescheduleFuture(days);else writeProgramme(days);editingDays=null;editing=false;setupOpen=false;calendarOpen=true;viewDate=new Date(new Date().getFullYear(),new Date().getMonth(),1);render(calendarPage())};
window.editProgramme=()=>{editing=true;editingDays=[...(programme()?.days||[])];setupOpen=true;render(setupPage())};
window.cancelProgrammeEdit=()=>{editingDays=null;editing=false;setupOpen=false;render(calendarPage())};
window.calendarMonth=n=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+n,1);render(calendarPage())};
window.calendarToday=()=>{const d=new Date();viewDate=new Date(d.getFullYear(),d.getMonth(),1);render(calendarPage())};
window.calendarDay=date=>{const x=schedule().find(q=>q.date===date);if(!x)return;const w=(window.PROGRAM||[]).find(q=>q.id===x.id);if(w&&typeof window.choose==='function')window.choose(x.id)};
function addCalendarButton(){if(calendarOpen||setupOpen)return;const n=document.querySelector('.nav');if(!n||n.querySelector('[data-calendar]'))return;const b=document.createElement('button');b.type='button';b.dataset.calendar='1';b.innerHTML='▣<span>Calendar</span>';b.onclick=()=>window.calendarNav('calendar');n.insertBefore(b,n.children[1]||null)}
function wrapStart(){if(startWrapped||typeof window.start!=='function')return;const original=window.start;window.start=()=>{const a=schedule(),done=completedDates(),td=today(),missed=a.filter(x=>x?.date<td&&!done.has(x.date)).sort((x,y)=>x.date.localeCompare(y.date)||String(x.id).localeCompare(String(y.id)))[0];if(missed){const todayWorkout=a.find(x=>x?.date===td),missedLabel=new Date(`${missed.date}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'long'}),takeMissed=window.confirm(`You missed Workout #${missed.id} on ${missedLabel}.\n\nOK = do the missed workout now\nCancel = skip it and do today's workout.`),target=takeMissed?missed:todayWorkout;if(target){try{const d=JSON.parse(localStorage.getItem('myTrainingDashboard')||'{}');d.selected=String(target.id);localStorage.setItem('myTrainingDashboard',JSON.stringify(d))}catch{}}}original()};startWrapped=true}
new MutationObserver(()=>{addCalendarButton();wrapStart()}).observe(document.documentElement,{childList:true,subtree:true});
setTimeout(()=>{addCalendarButton();wrapStart()},100);
setInterval(()=>{addCalendarButton();wrapStart()},500);
})();
