(()=>{
const S='myTrainingSchedule',P='myTrainingProgramme',D='myTrainingDashboard';
const pad=n=>String(n).padStart(2,'0');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=()=>iso(new Date());
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const labels=['MON','TUE','WED','THU','FRI','SAT','SUN'];
let view=new Date(new Date().getFullYear(),new Date().getMonth(),1),edit=false,days=[];
const app=()=>document.getElementById('app'), programme=()=>read(P)||{}, schedule=()=>read(S)||[];
const datesFor=(wanted,count,start)=>{const out=[],d=new Date(`${start}T12:00:00`);for(let i=0;out.length<count&&i<730;i++){if(wanted.includes((d.getDay()+6)%7))out.push(iso(d));d.setDate(d.getDate()+1)}return out};
const doneDates=()=>{const out=new Set(),d=read(D)||{};Object.entries(d.logs||{}).forEach(([k,v])=>{if(!v?.done)return;const key=String(k);const date=key.includes('::')?key.split('::')[0]:(v.date||v.completedOn);if(date)out.add(String(date).slice(0,10))});return out};
const nav=()=>`<nav class="nav standalone-nav"><a href="index.html?screen=home"><span class="standalone-nav-icon">⌂</span><span>Home</span></a><a class="active" href="calendar.html"><span class="standalone-nav-icon">▦</span><span>Calendar</span></a><a href="plan.html"><span class="standalone-nav-icon">☷</span><span>Plan</span></a><a href="index.html?screen=progress"><span class="standalone-nav-icon">⌁</span><span>Progress</span></a></nav>`;
function setup(){const p=programme();const chosen=edit?days:(p.days||[]);app().innerHTML=`<main class="shell programme-setup"><div class="top"><div><div class="eyebrow">My Training</div><div class="title">${edit?'Change training days':'Start your programme'}</div><div class="sub">20 workouts · 4 sessions per week</div></div></div><section class="card programme-card"><h2>Choose your training days</h2><p class="muted">${edit?'Completed and past sessions stay where they are. Only future sessions move.':'Choose the four days you normally want to train. Your 20-workout programme will be placed on those days.'}</p><div class="training-day-picker">${labels.map((x,i)=>`<button type="button" class="training-day ${chosen.includes(i)?'selected':''}" data-day="${i}"><b>${x}</b><span>${chosen.includes(i)?'✓':'+'}</span></button>`).join('')}</div><div class="programme-preview"><div><span class="muted">Programme</span><b>20 workouts</b></div><div><span class="muted">Frequency</span><b>4 days / week</b></div><div><span class="muted">First session</span><b>${chosen.length===4?new Date(`${datesFor(chosen,1,today())[0]}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'Choose 4 days'}</b></div></div><button type="button" class="primary programme-start" ${chosen.length===4?'':'disabled'} data-save>${edit?'Save training days':'Start programme'} <span>›</span></button>${edit?'<button type="button" class="text-link" data-cancel>Cancel</button>':''}</section></main>${nav()}`;}
function calendar(){const p=programme();if(!p.active)return setup();const a=schedule(),done=doneDates(),history=new Set(a.map(q=>q.originalDate).filter(Boolean)),y=view.getFullYear(),m=view.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,total=Math.ceil((offset+last.getDate())/7)*7;let cells='';for(let i=0;i<total;i++){const n=i-offset+1;if(n<1||n>last.getDate()){cells+='<div class="calendar-cell empty"></div>';continue}const date=`${y}-${pad(m+1)}-${pad(n)}`,x=a.find(q=>q.date===date),past=date<today(),isToday=date===today();let mark='',cls='';if(x){const isDone=done.has(date)||x.completedLater||x.completed;cls=isDone?'done':past?'missed':'workout';mark=cls==='missed'?'<span class="missed-x">×</span>':'<span class="calendar-dumbbell">⌁</span>'}else if(history.has(date)){cls='missed';mark='<span class="missed-x">×</span>'}else{const firstDate=a.map(q=>q.date).sort()[0],lastDate=a.map(q=>q.date).sort().at(-1);if(firstDate&&date>=firstDate&&date<=lastDate)mark='<span class="calendar-rest">R</span>'}cells+=`<button type="button" class="calendar-cell ${cls} ${isToday?'today':''}" data-date="${date}"><span class="calendar-number">${n}</span><span class="calendar-mark">${mark}</span></button>`}app().innerHTML=`<main class="shell calendar-modern"><section class="calendar-header"><div><h1>${view.toLocaleDateString('en-GB',{month:'long',year:'numeric'}).toUpperCase()}</h1><button type="button" class="calendar-edit" data-edit>Edit training days</button></div><div class="calendar-actions"><button type="button" data-prev aria-label="Previous month">‹</button><button type="button" class="calendar-today" data-today aria-label="Current month">⌂</button><button type="button" data-next aria-label="Next month">›</button></div></section><div class="calendar-weekdays">${labels.map(x=>`<span>${x[0]}</span>`).join('')}</div><div class="calendar-grid">${cells}</div></main>${nav()}`;}
function saveProgramme(){const chosen=days.slice().sort((a,b)=>a-b);if(chosen.length!==4)return;const old=schedule(),p=programme();if(!p.active){const ds=datesFor(chosen,window.PROGRAM.length,today());write(P,{active:true,days:chosen,startDate:ds[0],startedAt:new Date().toISOString()});write(S,window.PROGRAM.map((w,i)=>({id:w.id,date:ds[i]})));}else{const td=today(),done=doneDates(),fixed=old.filter(x=>x.date<=td||done.has(x.date)||x.completedLater||x.completed),moving=old.filter(x=>x.date>td&&!done.has(x.date)&&!x.completedLater&&!x.completed).sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.id).localeCompare(String(b.id))),blocked=new Set(fixed.map(x=>x.date)),start=new Date(`${td}T12:00:00`);start.setDate(start.getDate()+1);const ds=datesFor(chosen,moving.length,iso(start));let j=0;moving.forEach(x=>{while(ds[j]&&blocked.has(ds[j]))j++;if(ds[j])x.date=ds[j++]});write(P,{...p,days:chosen});write(S,[...fixed,...moving].sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.id).localeCompare(String(b.id))))}edit=false;days=[];calendar();}
app().addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.prev!==undefined){view=new Date(view.getFullYear(),view.getMonth()-1,1);calendar()}else if(b.dataset.next!==undefined){view=new Date(view.getFullYear(),view.getMonth()+1,1);calendar()}else if(b.dataset.today!==undefined){const d=new Date();view=new Date(d.getFullYear(),d.getMonth(),1);calendar()}else if(b.dataset.edit!==undefined){edit=true;days=[...(programme().days||[])];setup()}else if(b.dataset.day!==undefined){const i=+b.dataset.day,at=days.indexOf(i);if(at>=0)days.splice(at,1);else if(days.length<4)days.push(i);setup()}else if(b.dataset.cancel!==undefined){edit=false;days=[];calendar()}else if(b.dataset.save!==undefined)saveProgramme();else if(b.dataset.date){const x=schedule().find(q=>q.date===b.dataset.date);if(x){const d=read(D)||{};write(D,{...d,selected:x.id,screen:'workout'});location.href='index.html?screen=workout'}}});
calendar();
})();
