(()=>{
const KEY='myTrainingSchedule',PROGRAM_KEY='myTrainingProgramme';
const pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,today=()=>iso(new Date());
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const monthName=d=>d.toLocaleDateString('en-GB',{month:'long',year:'numeric'}).toUpperCase(),dayKey=(y,m,d)=>`${y}-${pad(m+1)}-${pad(d)}`;
const programme=()=>read(PROGRAM_KEY),schedule=()=>read(KEY)||[];
const completedDates=()=>{const out=new Set(),data=read('myTrainingDashboard');if(!data?.logs)return out;Object.entries(data.logs).forEach(([k,v])=>{if(v?.done){const p=k.split('::');if(p[0])out.add(p[0])}});return out};
const hasPR=v=>{if(!v||typeof v!=='object')return false;if(Array.isArray(v))return v.some(hasPR);return Object.entries(v).some(([k,x])=>/(^|_|-)(pr|personal.?best|personal.?record)(_|-|$)/i.test(k)&&(x===true||(Array.isArray(x)&&x.length)||(x&&typeof x==='object'))||hasPR(x))};
const prDates=()=>{const out=new Set(),data=read('myTrainingDashboard');if(!data?.logs)return out;Object.entries(data.logs).forEach(([k,v])=>{if(hasPR(v)){const p=k.split('::');if(p[0])out.add(p[0])}});return out};
const workoutForDate=(date,a)=>a.find(x=>x.date===date);
const icons={dumbbell:`<svg class="calendar-icon dumbbell" viewBox="0 0 44 30"><path d="M7 8v14M2 10v10M12 5v20M32 5v20M37 8v14M42 10v10M12 15h20" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`,trophy:`<svg class="calendar-icon trophy" viewBox="0 0 44 34"><path d="M14 4h16v8c0 6-3 10-8 10s-8-4-8-10V4Z" fill="none" stroke="currentColor" stroke-width="2.5"/><path d="M14 7H7v3c0 5 3 7 7 7M30 7h7v3c0 5-3 7-7 7M22 22v5M16 30h12" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,calendar:`<svg class="calendar-head-icon" viewBox="0 0 28 28"><rect x="3" y="5" width="22" height="20" rx="2" fill="none" stroke="currentColor" stroke-width="2.5"/><path d="M8 3v5M20 3v5M3 11h22" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><circle cx="19" cy="19" r="3" fill="currentColor"/></svg>`};
let calendarOpen=false,viewDate=new Date(new Date().getFullYear(),new Date().getMonth(),1),origGo=null,origStart=null,patched=false,setupOpen=false,editing=false;
function nextDates(days,count,start,blocked=new Set()){const out=[],d=new Date(`${start}T12:00:00`);for(let guard=0;out.length<count&&guard<730;guard++){const s=iso(d);if(days.includes((d.getDay()+6)%7)&&!blocked.has(s))out.push(s);d.setDate(d.getDate()+1)}return out}
function writeNewProgramme(days,start=today()){const dates=nextDates(days,PROGRAM.length,start);save(PROGRAM_KEY,{active:true,days,startDate:dates[0],startedAt:new Date().toISOString()});save(KEY,PROGRAM.map((w,i)=>({id:w.id,date:dates[i]})))}
function addDays(date,n){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return iso(d)}
function autoShiftMissed(){
 const a=schedule();if(!a.length)return;
 const done=completedDates();let changed=false,guard=0;
 while(guard++<100){
  const missed=a.filter(x=>x?.date<today()&&!done.has(x.date)).sort((x,y)=>x.date.localeCompare(y.date))[0];
  if(!missed)break;
  const from=missed.date;
  const moving=a.filter(x=>x?.date>=from&&!done.has(x.date)).sort((x,y)=>x.date.localeCompare(y.date)||String(x.id).localeCompare(String(y.id)));
  const occupied=new Set(a.filter(x=>done.has(x.date)).map(x=>x.date));
  moving.forEach(x=>{let next=addDays(x.date,1);while(occupied.has(next))next=addDays(next,1);x.date=next;occupied.add(next);});
  changed=true;
 }
 if(changed)save(KEY,a);
}
function rescheduleFuture(days){const old=schedule(),td=today(),completed=completedDates();const fixed=old.filter(x=>x?.date<=td||completed.has(x?.date));const fixedDates=new Set(fixed.map(x=>x.date));const moving=old.filter(x=>x?.date>td&&!completed.has(x?.date)).sort((a,b)=>String(a.id).localeCompare(String(b.id)));const dates=nextDates(days,moving.length,iso(new Date(Date.now()+86400000)),fixedDates);moving.forEach((x,i)=>{if(dates[i])x.date=dates[i]});save(PROGRAM_KEY,{...(programme()||{}),active:true,days});save(KEY,[...fixed,...moving].sort((a,b)=>String(a.id).localeCompare(String(b.id))));}
function setupPage(){const p=programme(),selected=p?.days||[],labels=['MON','TUE','WED','THU','FRI','SAT','SUN'],title=editing?'Change training days':'Start your programme',button=editing?'Save training days':'Start programme',copy=editing?'Completed and past sessions will stay where they are. Only future sessions will be moved to the new days.':'Choose the four days you normally want to train. Your 20-workout programme will be placed on those days. You can change them later if needed.';return `<main class="shell programme-setup"><div class="top"><div><div class="eyebrow">My Training</div><div class="title">${title}</div><div class="sub">20 workouts · 4 sessions per week</div></div></div><section class="card programme-card"><h2>Choose your training days</h2><p class="muted">${copy}</p><div class="training-day-picker">${labels.map((x,i)=>`<button type="button" class="training-day ${selected.includes(i)?'selected':''}" onclick="toggleTrainingDay(${i})"><b>${x}</b><span>${selected.includes(i)?'✓':'+'}</span></button>`).join('')}</div><div class="programme-preview"><div><span class="muted">Programme</span><b>20 workouts</b></div><div><span class="muted">Frequency</span><b>4 days / week</b></div><div><span class="muted">First session</span><b>${selected.length===4?new Date(`${nextDates(selected,1,today())[0]}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'Choose 4 days'}</b></div></div><button class="primary programme-start" ${selected.length===4?'':'disabled'} onclick="startProgramme()">${button} <span>›</span></button>${editing?'<button class="text-link" onclick="cancelProgrammeEdit()">Cancel <span>×</span></button>':''}</section></main>${nav('calendar')}`}
function calendarPage(){const p=programme();if(!p?.active)return setupPage();autoShiftMissed();const a=schedule(),done=completedDates(),prs=prDates(),y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,total=Math.ceil((offset+last.getDate())/7)*7;let cells='';for(let i=0;i<total;i++){const n=i-offset+1;if(n<1||n>last.getDate()){cells+='<div class="calendar-cell empty"></div>';continue}const date=dayKey(y,m,n),x=workoutForDate(date,a),completed=done.has(date),pr=prs.has(date),isToday=date===today(),past=date<today();let state=x?(completed?'workout':past?'missed':'workout future'):'';const icon=pr?icons.trophy:x?(completed?icons.dumbbell:past?'×':icons.dumbbell):'';cells+=`<button type="button" class="calendar-cell ${state} ${isToday?'today':''} ${pr?'pr':''}" aria-label="${esc(x?`Workout #${x.id}`:isToday?'Today':'No workout')}" onclick="calendarDay('${date}')"><span class="calendar-number">${n}</span><span class="calendar-mark">${icon}</span></button>`}return `<main class="shell calendar-modern"><section class="calendar-header"><div><h1>${monthName(viewDate)}</h1><button class="calendar-edit" onclick="editProgramme()">Edit training days</button></div><div class="calendar-actions"><button aria-label="Previous month" onclick="calendarMonth(-1)">‹</button><button type="button" class="calendar-today" aria-label="Go to current month" onclick="calendarToday()">${icons.calendar}</button><button aria-label="Next month" onclick="calendarMonth(1)">›</button></div></section><div class="calendar-weekdays"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div><div class="calendar-grid">${cells}</div></main>${nav('calendar')}`}
function nav(active){return `<nav class="nav"><button class="${active==='home'?'active':''}" onclick="calendarNav('home')">⌂<span>Home</span></button><button class="${active==='calendar'?'active':''}" onclick="calendarNav('calendar')">▣<span>Calendar</span></button><button class="${active==='plan'?'active':''}" onclick="calendarNav('plan')">☷<span>Plan</span></button><button class="${active==='progress'?'active':''}" onclick="calendarNav('progress')">⌁<span>Progress</span></button></nav>`}
function renderCalendar(){document.body.innerHTML=calendarPage()}
window.toggleTrainingDay=i=>{const p=programme()||{days:[]},days=[...(p.days||[])],at=days.indexOf(i);if(at>=0)days.splice(at,1);else if(days.length<4)days.push(i);else return;save(PROGRAM_KEY,{...(p||{}),days,active:Boolean(p?.active)});setupOpen=true;document.body.innerHTML=setupPage()};
window.startProgramme=()=>{const days=programme()?.days||[];if(days.length!==4)return;if(editing)rescheduleFuture(days);else writeNewProgramme(days);editing=false;setupOpen=false;calendarOpen=true;viewDate=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderCalendar()};
window.editProgramme=()=>{editing=true;setupOpen=true;document.body.innerHTML=setupPage()};
window.cancelProgrammeEdit=()=>{editing=false;setupOpen=false;renderCalendar()};
window.calendarMonth=n=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+n,1);renderCalendar()};
window.calendarToday=()=>{const d=new Date();viewDate=new Date(d.getFullYear(),d.getMonth(),1);renderCalendar()};
window.calendarDay=date=>{const x=schedule().find(q=>q.date===date);if(!x)return;const w=(window.PROGRAM||[]).find(q=>q.id===x.id);if(w&&typeof window.choose==='function')window.choose(x.id)};
window.calendarMove=(id,date)=>{const a=schedule(),x=a.find(q=>q.id===id);if(x&&date){x.date=date;save(KEY,a);renderCalendar()}};
window.calendarNav=s=>{if(s==='calendar'){calendarOpen=true;renderCalendar();return}calendarOpen=false;if(origGo)origGo(s)};
function patch(){if(typeof window.go==='function'&&!origGo){origGo=window.go;window.go=(s)=>s==='calendar'?window.calendarNav('calendar'):origGo(s)}if(typeof window.start==='function'&&!origStart){origStart=window.start;window.start=()=>{autoShiftMissed();if(!programme()?.active){setupOpen=true;editing=false;document.body.innerHTML=setupPage();return}origStart()}}if(!patched){patched=true;fixNav()}autoShiftMissed()}
function fixNav(){if(calendarOpen||setupOpen)return;const n=document.querySelector('.nav');if(!n||n.querySelector('[data-calendar]'))return;const b=document.createElement('button');b.dataset.calendar='1';b.innerHTML='▣<span>Calendar</span>';b.onclick=()=>calendarNav('calendar');n.insertBefore(b,n.children[1]||null)}
new MutationObserver(()=>{patch();if(calendarOpen&&!document.querySelector('.calendar-modern'))renderCalendar();else if(setupOpen&&!document.querySelector('.programme-setup'))document.body.innerHTML=setupPage();else fixNav()}).observe(document.documentElement,{childList:true,subtree:true});setInterval(patch,200);setTimeout(patch,500);
})();