const initial={weight:94.7,calories:2400,protein:200,selected:'01',logs:{},screen:'home'};
let state=JSON.parse(localStorage.getItem('myTrainingDashboard')||'null')||initial;
state.logs=state.logs||{}; state.screen=state.screen||'home'; state.selected=state.selected||'01';
const save=()=>localStorage.setItem('myTrainingDashboard',JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const getWorkout=id=>PROGRAM.find(w=>w.id===id)||PROGRAM[0];
const currentWorkout=()=>getWorkout(state.selected);
const reps=e=>{const x=e.reps.match(/\d+x(.+)/);return x?x[1].split(',').map(Number):[]};
const totalSets=w=>w.exercises.reduce((n,e)=>n+reps(e).length,0);
const logKey=(id,date)=>`${date||new Date().toISOString().slice(0,10)}::${id||state.selected}`;
const currentLog=()=>state.logs[logKey()]||{sets:{},done:false};
const previousLog=id=>{const ks=Object.keys(state.logs).filter(k=>k.endsWith(`::${id}`)).sort().reverse();return ks.length?state.logs[ks[0]]:null};
const previousCompleted=()=>{const ks=Object.keys(state.logs).filter(k=>state.logs[k].done).sort().reverse();return ks.length?{id:ks[0].split('::')[1],log:state.logs[ks[0]]}:null};
function go(screen){state.screen=screen;save();render()}
function choose(id){state.selected=id;state.screen='workout';save();render()}
function start(){state.screen='workout';save();render()}
function setValue(ei,si,field,value){const l=currentLog();l.sets[ei]=l.sets[ei]||{};l.sets[ei][si]=l.sets[ei][si]||{};l.sets[ei][si][field]=value===''?'':Number(value);l.sets[ei][si].completed=Boolean(l.sets[ei][si].weight!==''&&l.sets[ei][si].weight!=null&&l.sets[ei][si].reps!==''&&l.sets[ei][si].reps!=null);state.logs[logKey()]=l;save();render()}
function toggle(ei,si){const l=currentLog();l.sets[ei]=l.sets[ei]||{};l.sets[ei][si]=l.sets[ei][si]||{};l.sets[ei][si].completed=!l.sets[ei][si].completed;state.logs[logKey()]=l;save();render()}
function finish(){const l=currentLog();l.done=true;state.logs[logKey()]=l;save();render()}
function saveWeight(){const v=Number(document.getElementById('weight').value);if(v>0){state.weight=v;save();render()}}
function nav(active){return `<nav class="nav"><button class="${active==='home'?'active':''}" onclick="go('home')">⌂<span>Home</span></button><button class="${active==='workout'?'active':''}" onclick="go('workout')">▥<span>Workouts</span></button><button class="${active==='plan'?'active':''}" onclick="go('plan')">☷<span>Plan</span></button><button class="${active==='progress'?'active':''}" onclick="go('progress')">⌁<span>Progress</span></button></nav>`}
function preview(w,label,action){return `<article class="dash-card"><div class="card-top"><div><div class="eyebrow">${label}</div><h2>Workout #${w.id}</h2><div class="sub">${w.type} · ${w.exercises.length} exercises · ${totalSets(w)} total sets</div></div>${action}</div><div class="divider"></div><div class="preview-label">PREVIEW · FIRST 3 EXERCISES</div>${w.exercises.slice(0,3).map((e,i)=>`<div class="preview-row"><span class="num">${i+1}</span><div><b>${esc(e.name)}</b><div class="muted">${esc(e.reps)}</div></div></div>`).join('')}<button class="text-link" onclick="choose('${w.id}')">View full workout <span>›</span></button></article>`}
function home(){const today=currentWorkout();const next=PROGRAM[(PROGRAM.findIndex(w=>w.id===today.id)+1)%PROGRAM.length];const pc=previousCompleted();const previous=pc?getWorkout(pc.id):PROGRAM[(PROGRAM.findIndex(w=>w.id===today.id)-1+PROGRAM.length)%PROGRAM.length];return `<main class="shell dashboard"><header class="dash-head"><div><div class="eyebrow">My Training</div><div class="greeting">Your training dashboard</div><h1>Today, ${new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</h1></div><div class="head-actions"><button onclick="go('plan')">☷</button></div></header><div class="week">${['M','T','W','T','F','S','S'].map((d,i)=>`<span class="${i===((new Date().getDay()+6)%7)?'selected':''}">${d}</span>`).join('')}</div>${preview(today,"TODAY'S WORKOUT",`<button class="primary" onclick="start()">Start workout <span>›</span></button>`)}${preview(previous,'PREVIOUS WORKOUT',`<span class="status">${pc?'Completed':'Previous'}</span>`)}${preview(next,'UP NEXT',`<span class="status">Upcoming</span>`)}<article class="activity"><span class="plus">+</span><div><b>Log activity</b><div class="muted">Track cardio, steps, mobility and more.</div></div><span>›</span></article></main>${nav('home')}`}
function workout(){const w=currentWorkout(),l=currentLog();let done=0;Object.keys(l.sets).forEach(e=>Object.values(l.sets[e]||{}).forEach(s=>{if(s.completed)done++}));const total=totalSets(w),pct=total?Math.round(done/total*100):0;return `<main class="shell"><div class="top"><div><div class="eyebrow">My Training · Phase 1</div><div class="title">Workout #${w.id}</div><div class="sub">${w.type} · ${w.exercises.length} exercises</div></div></div><div class="card picker"><label>Workout</label><select onchange="choose(this.value)">${PROGRAM.map(x=>`<option value="${x.id}" ${x.id===w.id?'selected':''}>#${x.id} · ${x.type}</option>`).join('')}</select></div><div class="card hero"><div><div class="muted">Workout progress</div><div class="progressbar"><span style="width:${pct}%"></span></div><b>${done}/${total} sets · ${pct}%</b></div><button class="primary" onclick="finish()">${l.done?'Completed ✓':'Finish workout'}</button></div><section class="section">${w.exercises.map((e,ei)=>exercise(e,ei)).join('')}</section></main>${nav('workout')}`}
function exercise(e,ei){const targets=reps(e),last=previousLog(currentWorkout().id),prev=(last&&last.sets&&last.sets[ei])||{},cur=currentLog().sets[ei]||{};const lastText=targets.map((_,i)=>prev[i]&&prev[i].weight!==''&&prev[i].reps!==''?`${prev[i].weight}kg × ${prev[i].reps}`:'—').join(' · ');return `<article class="card exercise-card"><div class="exercise-head"><div><div class="exercise-name"><span class="index">${ei+1}</span><h3>${esc(e.name)}</h3></div><div class="muted">Programme: ${esc(e.reps)}</div></div><span class="pill">${targets.filter((_,i)=>cur[i]&&cur[i].completed).length}/${targets.length}</span></div><div class="previous"><span>Last time</span><b>${last?lastText:'No previous log'}</b></div><div class="recommendation"><strong>Next:</strong> Keep the programme fixed at ${targets.join(', ')} reps. Progress by load only when the prescribed reps are completed with good form.</div><div class="log-head"><span>SET</span><span>KG</span><span>TARGET</span><span>ACTUAL REPS</span><span></span></div>${targets.map((target,si)=>{const d=cur[si]||{},p=prev[si]||{};return `<div class="set-row"><span class="set-num">${si+1}</span><input inputmode="decimal" type="number" step="0.5" placeholder="${p.weight??'kg'}" value="${d.weight??''}" onchange="setValue(${ei},${si},'weight',this.value)"><span class="target">${target}</span><input inputmode="numeric" type="number" step="1" placeholder="${target}" value="${d.reps??''}" onchange="setValue(${ei},${si},'reps',this.value)"><button class="check ${d.completed?'checked':''}" onclick="toggle(${ei},${si})">${d.completed?'✓':'○'}</button></div>`}).join('')}</article>`}
function plan(){return `<main class="shell"><div class="top"><div><div class="eyebrow">Phase 1</div><div class="title">20-workout plan</div><div class="sub">The programme from your video · prescribed reps stay fixed</div></div></div>${PROGRAM.map(w=>`<article class="card"><h2>Workout #${w.id}</h2><div class="muted">${w.type}</div>${w.exercises.map(e=>`<div class="plan-row"><div><b>${esc(e.name)}</b><div class="muted">${esc(e.reps)}</div></div></div>`).join('')}<button class="text-link" onclick="choose('${w.id}')">Open workout <span>›</span></button></article>`).join('')}</main>${nav('plan')}`}
function progress(){const completed=Object.values(state.logs).filter(x=>x.done).length;return `<main class="shell"><div class="top"><div><div class="eyebrow">Progress</div><div class="title">Training history</div><div class="sub">Performance and bodyweight</div></div></div><div class="grid"><div class="stat"><div class="muted">Bodyweight</div><b>${Number(state.weight).toFixed(1)} kg</b></div><div class="stat"><div class="muted">Completed</div><b>${completed}</b></div><div class="stat"><div class="muted">Calories</div><b>${state.calories}</b></div><div class="stat"><div class="muted">Protein</div><b>${state.protein} g</b></div></div><div class="card"><h3>Log bodyweight</h3><div class="form"><input id="weight" type="number" step="0.1" value="${state.weight}"><button class="primary" onclick="saveWeight()">Save</button></div></div></main>${nav('progress')}`}
function render(){const html=state.screen==='home'?home():state.screen==='workout'?workout():state.screen==='plan'?plan():progress();document.body.innerHTML=html}
render();