(()=>{
const KEY='myTrainingDashboard',SUMMARY='myTrainingLastSummary';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{logs:{}}}catch{return{logs:{}}}};
const write=d=>localStorage.setItem(KEY,JSON.stringify(d));const programme=()=>window.PROGRAM||[];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function metrics(sets){const a=Object.values(sets||{}).filter(x=>x?.completed&&Number(x.weight)>0&&Number(x.reps)>0).map(x=>({weight:Number(x.weight),reps:Number(x.reps)}));return{sets:a,bestWeight:a.length?Math.max(...a.map(x=>x.weight)):0,bestReps:a.length?Math.max(...a.map(x=>x.reps)):0,volume:a.reduce((n,x)=>n+x.weight*x.reps,0)}}
function analyse(logKey){const d=read(),log=d.logs?.[logKey];if(!log?.done)return null;const [date,wid]=logKey.split('::'),w=programme().find(x=>x.id===wid);if(!w)return null;const earlier=Object.entries(d.logs||{}).filter(([k,v])=>v?.done&&k!==logKey&&k.localeCompare(logKey)<0);const achievements=[];let totalVolume=0,totalSets=0;w.exercises.forEach((e,ei)=>{const now=metrics(log.sets?.[ei]);if(!now.sets.length)return;totalVolume+=now.volume;totalSets+=now.sets.length;let oldWeight=0,oldReps=0,oldVolume=0,seen=false;earlier.forEach(([k,v])=>{const ow=programme().find(x=>x.id===k.split('::')[1]);if(!ow)return;ow.exercises.forEach((oe,oi)=>{if(oe.name!==e.name)return;const m=metrics(v.sets?.[oi]);if(!m.sets.length)return;seen=true;oldWeight=Math.max(oldWeight,m.bestWeight);oldReps=Math.max(oldReps,m.bestReps);oldVolume=Math.max(oldVolume,m.volume)})});if(!seen)achievements.push({type:'baseline',exercise:e.name,text:'Baseline established'});else if(now.bestWeight>oldWeight)achievements.push({type:'weight',exercise:e.name,text:`Weight PR · ${now.bestWeight} kg`});else if(now.bestReps>oldReps)achievements.push({type:'reps',exercise:e.name,text:`Rep PR · ${now.bestReps} reps`});else if(oldVolume>0&&now.volume>oldVolume*1.025)achievements.push({type:'volume',exercise:e.name,text:`Volume PR · ${Math.round(now.volume)} kg`})});return{date,wid,type:w.type,totalVolume:Math.round(totalVolume),totalSets,achievements}}
function saveSummary(logKey){const s=analyse(logKey);if(s)localStorage.setItem(SUMMARY,JSON.stringify(s));return s}
function latestCompleted(){const d=read();return Object.entries(d.logs||{}).filter(([,v])=>v?.done).sort((a,b)=>b[0].localeCompare(a[0]))[0]||null}
function reconcile(){const d=read(),last=latestCompleted();if(!last)return;const [k]=last;let s;try{s=JSON.parse(localStorage.getItem(SUMMARY)||'null')}catch{}if(!s||`${s.date}::${s.wid}`!==k)saveSummary(k);const completedIds=new Set(Object.entries(d.logs||{}).filter(([,v])=>v?.done).map(([key])=>key.split('::')[1]));const ordered=programme();const firstPending=ordered.find(w=>!completedIds.has(w.id));if(firstPending&&d.selected!==firstPending.id&&!d.activeWorkout){d.selected=firstPending.id;write(d)}}
function renderSummary(){reconcile();let s;try{s=JSON.parse(localStorage.getItem(SUMMARY)||'null')}catch{}if(!s)return;const app=document.getElementById('app');if(!app||document.querySelector('.workout-summary-card'))return;const main=app.querySelector('main.dashboard');if(!main)return;const card=document.createElement('article');card.className='dash-card workout-summary-card';const wins=s.achievements.filter(x=>x.type!=='baseline');card.innerHTML=`<div class="eyebrow">WORKOUT #${esc(s.wid)} COMPLETE</div><h2>Workout complete</h2><div class="summary-stats"><span><b>${s.totalSets}</b><small>sets</small></span><span><b>${s.totalVolume.toLocaleString()}</b><small>kg volume</small></span><span><b>${wins.length}</b><small>PR${wins.length===1?'':'s'}</small></span></div>${s.achievements.length?`<div class="summary-prs">${s.achievements.map(x=>`<div class="summary-pr ${x.type}"><span>${x.type==='weight'?'↑':x.type==='reps'?'+':x.type==='volume'?'◆':'✓'}</span><div><b>${esc(x.exercise)}</b><small>${esc(x.text)}</small></div></div>`).join('')}</div>`:'<div class="muted">Workout logged. Keep building from here.</div>'}`;main.insertBefore(card,main.querySelector('.dash-card')||null)}
function detectCompletion(){const last=latestCompleted();if(!last)return;let s;try{s=JSON.parse(localStorage.getItem(SUMMARY)||'null')}catch{}if(!s||`${s.date}::${s.wid}`!==last[0])saveSummary(last[0]);renderSummary()}
const obs=new MutationObserver(()=>requestAnimationFrame(detectCompletion));const app=document.getElementById('app');if(app)obs.observe(app,{childList:true,subtree:true});requestAnimationFrame(detectCompletion);
window.MyTrainingPR={analyse,saveSummary,reconcile};
})();