(()=>{
const dash=()=>{try{return JSON.parse(localStorage.getItem('myTrainingDashboard')||'null')||{logs:{}}}catch{return{logs:{}}}};
const programme=()=>window.PROGRAM||[];
const completedLogs=()=>Object.entries(dash().logs||{}).filter(([,v])=>v?.done).sort((a,b)=>a[0].localeCompare(b[0]));
const increment=name=>/dumbbell/i.test(name)?1:2.5;
function sessionsFor(name){const out=[];completedLogs().forEach(([key,log])=>{const [date,wid]=key.split('::'),w=programme().find(x=>x.id===wid);if(!w)return;w.exercises.forEach((e,ei)=>{if(e.name!==name)return;const sets=Object.values(log.sets?.[ei]||{}).filter(s=>s?.completed&&Number(s.weight)>0&&Number(s.reps)>0).map(s=>({weight:Number(s.weight),reps:Number(s.reps)}));if(sets.length)out.push({date,wid,sets,bestWeight:Math.max(...sets.map(s=>s.weight)),volume:sets.reduce((n,s)=>n+s.weight*s.reps,0)})})});return out.sort((a,b)=>a.date.localeCompare(b.date))}
function analyse(name){const history=sessionsFor(name);if(!history.length)return{status:'new',label:'Establish baseline',message:'First logged session — establish a solid baseline before progressing.',next:null,last:null};const last=history.at(-1),prev=history.at(-2);if(!prev)return{status:'baseline',label:`Repeat ${last.bestWeight} kg`,message:'Baseline recorded. Repeat this performance cleanly before increasing load.',next:last.bestWeight,last};const lastTop=Math.max(...last.sets.map(s=>s.reps)),prevTop=Math.max(...prev.sets.map(s=>s.reps));const weightUp=last.bestWeight>prev.bestWeight,volumeUp=last.volume>prev.volume*1.025,repsUp=last.bestWeight===prev.bestWeight&&lastTop>prevTop;if(weightUp)return{status:'progress',label:`Hold ${last.bestWeight} kg`,message:`Load progressed from ${prev.bestWeight} kg to ${last.bestWeight} kg. Hold this load until the prescribed reps are secure.`,next:last.bestWeight,last};if(repsUp||volumeUp){const next=last.bestWeight+increment(name);return{status:'ready',label:`Next target ${next.toFixed(1)} kg`,message:`Performance improved at ${last.bestWeight} kg. If all prescribed reps felt controlled, next time try ${next.toFixed(1)} kg.`,next,last};}return{status:'hold',label:`Hold ${last.bestWeight} kg`,message:`Hold ${last.bestWeight} kg next time and aim to improve reps or execution before adding load.`,next:last.bestWeight,last}}
function prefill(name,count){const a=analyse(name);if(!Number.isFinite(a.next))return false;let changed=false;try{const d=dash(),state=d,selected=state.selected,w=programme().find(x=>x.id===selected);if(!w)return false;const ei=w.exercises.findIndex(e=>e.name===name);if(ei<0)return false;const key=`${new Date().toISOString().slice(0,10)}::${selected}`,log=state.logs[key]||{sets:{},done:false};log.sets[ei]=log.sets[ei]||{};for(let i=0;i<count;i++){log.sets[ei][i]=log.sets[ei][i]||{};if(log.sets[ei][i].weight==null||log.sets[ei][i].weight===''){log.sets[ei][i].weight=a.next;changed=true}}if(changed){state.logs[key]=log;localStorage.setItem('myTrainingDashboard',JSON.stringify(state))}}catch{}return changed}
window.MyTrainingProgression={sessionsFor,analyse,prefill};
})();