(function(){
const U=window.SUPABASE_URL,K=window.SUPABASE_ANON_KEY;let client=null;
function getClient(){if(!client){if(!window.supabase||!window.supabase.createClient)throw Error('Supabase client failed to load');client=window.supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}})}return client}
async function auth(){const c=getClient();const g=await c.auth.getSession();if(g.data&&g.data.session)return g.data.session;const r=await c.auth.signInAnonymously();if(r.error)throw r.error;if(!r.data.session)throw Error('Anonymous sign-in returned no session');return r.data.session}
async function load(){const c=getClient();await auth();const r=await c.from('bodyweight_logs').select('logged_on,weight_kg').order('logged_on',{ascending:false}).limit(60);if(r.error)throw r.error;state.weights=r.data||[];if(state.weights[0])state.weight=Number(state.weights[0].weight_kg);state.syncError='';save();return state.weights}
function note(rows){if(!rows.length)return 'Start logging your morning weight. We will judge progress from the trend, not a single weigh-in.';const a=rows.slice(0,7).map(x=>+x.weight_kg),avg=a.reduce((x,y)=>x+y,0)/a.length,b=rows.slice(7,14).map(x=>+x.weight_kg);if(!b.length)return `Your current ${a.length}-day average is ${avg.toFixed(1)} kg. Keep 2,400 kcal and 200 g protein consistent while we build the trend.`;const p=b.reduce((x,y)=>x+y,0)/b.length,d=avg-p;if(d<-.15)return `Your 7-day average is down ${Math.abs(d).toFixed(1)} kg. Keep 2,400 kcal and 200 g protein steady today.`;if(d>.15)return `Your 7-day average is up ${d.toFixed(1)} kg. Don't react to one week alone — keep 2,400 kcal and 200 g protein consistent and reassess the trend.`;return 'Your weight trend is broadly stable. Keep 2,400 kcal and 200 g protein consistent and let the trend develop.'}
window.saveWeight=async function(){const v=Number(document.getElementById('weight').value);if(!(v>0))return;try{const c=getClient(),s=await auth(),date=new Date().toISOString().slice(0,10);const r=await c.from('bodyweight_logs').upsert({logged_on:date,weight_kg:v,user_id:s.user.id},{onConflict:'user_id,logged_on'});if(r.error)throw r.error;state.weight=v;await load();state.syncError='';save();render()}catch(e){state.weight=v;state.syncError=e&&e.message?e.message:'Secure sync failed';save();render()}}
window.progress=function(){const completed=Object.values(state.logs).filter(x=>x.done).length;const rows=state.weights||[];const n=note(rows);const err=state.syncError?String(state.syncError).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])):'';const status=err?`<div class="muted" style="margin-top:8px">Sync status: ${err}</div>`:'<div class="muted" style="margin-top:8px">Securely synced to your account.</div>';return `<main class="shell"><div class="top"><div><div class="eyebrow">Progress</div><div class="title">Training history</div><div class="sub">Performance and bodyweight</div></div></div><div class="grid"><div class="stat"><div class="muted">Bodyweight</div><b>${Number(state.weight).toFixed(1)} kg</b></div><div class="stat"><div class="muted">Completed</div><b>${completed}</b></div><div class="stat"><div class="muted">Calories</div><b>${state.calories}</b></div><div class="stat"><div class="muted">Protein</div><b>${state.protein} g</b></div></div><div class="card"><h3>Log bodyweight</h3><div class="form"><input id="weight" type="number" step="0.1" value="${state.weight}"><button class="primary" onclick="saveWeight()">Save</button></div><div class="recommendation" style="margin-top:16px"><strong>Today's feedback</strong><div style="margin-top:6px">${n}</div>${status}</div></div></main>${nav('progress')}`}
load().then(()=>{if(state.screen==='progress')render()}).catch(e=>{state.syncError=e&&e.message?e.message:'Secure sync failed';save();if(state.screen==='progress')render()});
})();
