(function(){
const U=window.SUPABASE_URL,K=window.SUPABASE_ANON_KEY,S='myTrainingSupabaseSession';
async function auth(){let s=null;try{s=JSON.parse(localStorage.getItem(S)||'null')}catch{}if(s&&s.access_token)return s;const client=window.supabase.createClient(U,K);const r=await client.auth.signInAnonymously();if(r.error)throw r.error;s=r.data.session;if(!s)throw Error('Anonymous sign-in unavailable');localStorage.setItem(S,JSON.stringify(s));return s}
async function api(path,opt={}){const s=await auth();const r=await fetch(U+path,{...opt,headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok){let m='Sync failed';try{const j=await r.json();m=j.message||j.hint||j.details||j.error||m}catch{}throw Error(m)}return r.status===204?null:r.json()}
async function load(){try{const rows=await api('/rest/v1/bodyweight_logs?select=id,logged_on,weight_kg&order=logged_on.desc&limit=60');state.weights=rows||[];if(rows&&rows[0])state.weight=Number(rows[0].weight_kg);save();return rows||[]}catch{return state.weights||[]}}
function note(rows){if(!rows.length)return 'Start logging your morning weight. We will judge progress from the trend, not a single weigh-in.';const a=rows.slice(0,7).map(x=>+x.weight_kg),avg=a.reduce((x,y)=>x+y,0)/a.length,b=rows.slice(7,14).map(x=>+x.weight_kg);if(!b.length)return `Your current ${a.length}-day average is ${avg.toFixed(1)} kg. Keep 2,400 kcal and 200 g protein consistent while we build the trend.`;const p=b.reduce((x,y)=>x+y,0)/b.length,d=avg-p;if(d<-.15)return `Your 7-day average is down ${Math.abs(d).toFixed(1)} kg. Keep 2,400 kcal and 200 g protein steady today.`;if(d>.15)return `Your 7-day average is up ${d.toFixed(1)} kg. Don't react to one week alone — keep 2,400 kcal and 200 g protein consistent and reassess the trend.`;return 'Your weight trend is broadly stable. Keep 2,400 kcal and 200 g protein consistent and let the trend develop.'}
window.saveWeight=async function(){const v=Number(document.getElementById('weight').value);if(!(v>0))return;const date=new Date().toISOString().slice(0,10);try{const s=await auth();const existing=await api(`/rest/v1/bodyweight_logs?select=id&logged_on=eq.${date}&limit=1`);if(existing&&existing[0]){await api(`/rest/v1/bodyweight_logs?id=eq.${existing[0].id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({weight_kg:v})})}else{await api('/rest/v1/bodyweight_logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({logged_on:date,weight_kg:v,user_id:s.user.id})})}state.weight=v;const rows=await load();render();setTimeout(()=>{const box=document.getElementById('weightFeedback');if(box)box.textContent=note(rows);const status=document.getElementById('syncStatus');if(status)status.textContent='Securely synced to your account.'},0)}catch(e){state.weight=v;save();render();setTimeout(()=>{const box=document.getElementById('weightFeedback');if(box)box.textContent='Saved locally. Sync error: '+e.message},0)}};
const baseProgress=window.progress;window.progress=function(){let h=baseProgress();const n=note(state.weights||[]);if(h.includes('id="weightFeedback"'))return h;h=h.replace('</div></main>',`<div class="recommendation" style="margin-top:16px"><strong>Today's feedback</strong><div id="weightFeedback" style="margin-top:6px">${n}</div></div><div id="syncStatus" class="muted" style="margin-top:10px">${state.weights?.length?'Securely synced to your account.':''}</div></div></main>`);return h};
load();
})();
