(function(){
const escH=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function localHistory(){return Object.entries(state.logs||{}).filter(([k,v])=>v&&v.done).map(([k,v])=>{const [date,id]=k.split('::');return {date,id,log:v}}).sort((a,b)=>b.date.localeCompare(a.date));}
function historyCard(x){const w=PROGRAM.find(p=>p.id===x.id);if(!w)return '';const sets=x.log.sets||{};return `<details class="card history-card"><summary><div><b>Workout #${escH(x.id)} · ${escH(w.type)}</b><div class="muted">${new Date(x.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</div></div><span class="status">Completed ✓</span></summary><div class="history-detail">${w.exercises.map((e,ei)=>{const target=reps(e),ss=sets[ei]||{};return `<div class="history-exercise"><b>${escH(e.name)}</b>${target.map((_,si)=>{const s=ss[si]||{};return `<div class="history-set"><span>Set ${si+1}</span><span>${s.weight!==''&&s.weight!=null?s.weight+' kg':'—'}</span><span>${s.reps!==''&&s.reps!=null?s.reps+' reps':'—'}</span></div>`}).join('')}</div>`}).join('')}</div></details>`}
function historyMarkup(){const items=localHistory();return `<section class="section"><div class="section-head"><div><div class="eyebrow">Training log</div><h2>Workout history</h2></div><span class="muted">${items.length} completed</span></div>${items.length?items.map(historyCard).join(''):'<div class="card"><div class="muted">No completed workouts yet.</div></div>'}</section>`}
const originalFinish=window.finish;window.finish=function(){if(currentLog().done){render();return}const w=currentWorkout();const ok=window.confirm(`Finish Workout #${w.id}? This will save it as completed.`);if(!ok)return;originalFinish();};
const originalProgress=window.progress;window.progress=function(){let h=originalProgress();return h.replace('</main>',historyMarkup()+'</main>')};
const originalPlan=window.plan;window.plan=function(){let h=originalPlan();const done=new Set(localHistory().map(x=>x.id));return h.replace(/<article class="card"><h2>Workout #(\d+)<\/h2>/g,(m,id)=>`<article class="card"><h2>Workout #${id}</h2>${done.has(id)?'<div class="status">Completed ✓</div>':''}`)};
async function loadRemote(){try{const txt=await fetch(new URL('supabase-config.js?v=9',document.baseURI)).then(r=>r.text());const U=(txt.match(/SUPABASE_URL='([^']+)'/)||[])[1],K=(txt.match(/SUPABASE_ANON_KEY='([^']+)'/)||[])[1];if(!U||!K)return;let s=null;try{s=JSON.parse(localStorage.getItem('myTrainingSupabaseSession')||'null')}catch{}if(!s?.access_token)return;const r=await fetch(U+'/rest/v1/workout_logs?select=workout_date,workout_id,workout_type,sets,completed&completed=eq.true&order=workout_date.desc&limit=100',{headers:{apikey:K,Authorization:'Bearer '+s.access_token}});if(!r.ok)return;const rows=await r.json();rows.forEach(x=>{const k=`${x.workout_date}::${x.workout_id}`;state.logs[k]={sets:x.sets||{},done:true};});save();if(state.screen==='progress'||state.screen==='plan')render()}catch(e){}}
loadRemote();
})();